@startuml Utilisation

actor Player
actor Admin

rectangle "Système" {
  
  ' Cas d'utilisation Player
  Player --> (Inscription)
  Player --> (Parcourir les techniques)
  Player --> (Faire une action)
  (Faire une action) --> (Action réussie)
  (Faire une action) --> (Action échec)
  Player --> (Message action)
  
  ' Cas d'utilisation Admin
  Admin --> (Ajouter une fonctionnalité)
  (Ajouter une fonctionnalité) --> (Fonctionnalité marche)
  (Ajouter une fonctionnalité) --> (Fonctionnalité ne marche pas)
  (Fonctionnalité ne marche pas) --> (Résout problème fonctionnalité)
  (Résout problème fonctionnalité) --> (Ajout fonctionnalité)
  (Fonctionnalité ne marche pas) --> (Vérifie si c’est un bug)
  (Vérifie si c’est un bug) --> (Bug trouvé)
  (Bug trouvé) --> (Résout bug)
  (Résout bug) --> (Test bug)
  (Test bug) --> (Jeu fonctionnel)
}

@enduml
