@startuml sequence
|= Player |
start
:Inscription;
:Parcourir les rubriques;
:Faire une action;

if (Action réussie ?) then (Oui)
  :Action réussie;
else
  :Action échec;
endif

:Message action;
stop

|= Admin |
start
:Consulter rubriques;
:Consulter les quêtes;
:Créer une quête;
:Ajouter une quête;
:Ajouter un monstre;
:Ajouter une fonctionnalité;
:Consulter joueurs;
:Consulter monstres;

:Tester une fonctionnalité;

if (Fonctionnalité marche ?) then (Oui)
  :Jeu fonctionnel;
else
  :Fonctionnalité ne marche pas;
  :Patcher et régler bug;

  if (Bug corrigé ?) then (Oui)
    :Retester la fonctionnalité;
    :Fonctionnalité OK;
  else
    :Escalade ou log erreur;
  endif
endif
stop
@enduml
